// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhesqvoqppfgunrafbiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoZXNxdm9xcHBmZ3VucmFmYml1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjQ2MjgsImV4cCI6MjA2Mzg0MDYyOH0.bX7rRzLS2UsCUFOOSVo86GQ3wNe4HG0KR_FEV-Cnz0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);